.github/workflows/aws-terraform.yml
cloud_AWS/README.md
cloud_AWS/terraform/module/README.md
cloud_AWS/terraform/module/examples/all-vpc-from-region/README.md
cloud_AWS/terraform/module/examples/all-vpc-from-region/main.tf
cloud_AWS/terraform/module/examples/all-vpc-from-region/output.tf
cloud_AWS/terraform/module/examples/boutique-eks/README.md
cloud_AWS/terraform/module/examples/boutique-eks/main.tf
cloud_AWS/terraform/module/examples/boutique-eks/outputs.tf
cloud_AWS/terraform/module/examples/boutique-eks/variables.tf
cloud_AWS/terraform/module/examples/single-vpc/README.md
cloud_AWS/terraform/module/examples/single-vpc/main.tf
cloud_AWS/terraform/module/examples/single-vpc/output.tf
cloud_AWS/terraform/module/examples/single-vpc/variables.tf
cloud_AWS/terraform/module/iam.tf
cloud_AWS/terraform/module/output.tf
cloud_AWS/terraform/module/s3.tf
cloud_AWS/terraform/module/tests/main.tf
cloud_AWS/terraform/module/variables.tf

This Terraform module will create S3 bucket for each VPC it suppose to configure. It can configure one or more VPCs located in the same region.

Terraform module to make VPC configuration easier

---

.github/workflows/aws-ansible.yml
cloud_AWS/README.md
cloud_AWS/ansible/role/README.md
cloud_AWS/ansible/role/defaults/main.yml
cloud_AWS/ansible/role/examples/single-vpc/README.md
cloud_AWS/ansible/role/examples/single-vpc/inventory.yml
cloud_AWS/ansible/role/examples/single-vpc/main.yml
cloud_AWS/ansible/role/files/aws_iam_ec2_access_policy.json
cloud_AWS/ansible/role/files/aws_iam_role.json
cloud_AWS/ansible/role/files/aws_iam_s3_ro_access_policy.json
cloud_AWS/ansible/role/files/aws_iam_s3_rw_access_policy.json
cloud_AWS/ansible/role/files/aws_s3_public_access.json
cloud_AWS/ansible/role/files/aws_vpc_flow_logs.json
cloud_AWS/ansible/role/handlers/main.yml
cloud_AWS/ansible/role/meta/main.yml
cloud_AWS/ansible/role/tasks/assert.yml
cloud_AWS/ansible/role/tasks/ec2.yml
cloud_AWS/ansible/role/tasks/iam.yml
cloud_AWS/ansible/role/tasks/main.yml
cloud_AWS/ansible/role/tasks/s3.yml
cloud_AWS/ansible/role/tests/inventory.yml
cloud_AWS/ansible/role/tests/main.yml
cloud_AWS/ansible/role/tests/roles/test_vpcs/tasks/main.yml
cloud_AWS/ansible/role/vars/main.yml

This Ansible role will create S3 bucket for each VPC it suppose to configure. It can configure one or more VPCs located in the same region.

Ansible role to make VPC configuration easier

---

.github/workflows/aws-terraform.yml
cloud_AWS/ansible/role/README.md
cloud_AWS/ansible/role/defaults/main.yml
cloud_AWS/ansible/role/tasks/iam.yml

This PR fixes issue with the variable names for S3 RW access

Fixing variable nam and LocalStack version

---

cloud_AWS/terraform/module/README.md

Fixing link reference for terraform demo in terraform readme file.

Fixing link reference for terraform demo

---

cloud_AWS/terraform/module/examples/sock-shop-eks/README.md
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/1-sock-shop-install/1-sock-shop-complete-demo-istio.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/1-sock-shop-install/2-sockshop-gateway.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/1-sock-shop-install/3-virtual-services-all.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/1-sock-shop-install/frontend-load-balancer.yml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/1-sock-shop-install/sock-shop-complete-demo.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-canary.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-canary.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-front-end-deployment-v1-istio.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-front-end-deployment-v1-route.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-front-end-deployment-v1.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-front-end-deployment-v2-istio.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-front-end-deployment-v2-route.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/2-inteligent-routing/2-front-end-deployment-v2.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/3-circuit-breaker/3-circuit-breaker.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/3-circuit-breaker/3-fortio.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/4-security/4-global-mtls-mesh-policy.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/4-security/4-virtual-services-all-mtls.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/5-timeouts/5-fault-injection-abort-catalogue.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/README.md
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/sock-shop-complete-demo-istio-1.yaml
cloud_AWS/terraform/module/examples/sock-shop-eks/main.tf
cloud_AWS/terraform/module/examples/sock-shop-eks/outputs.tf
cloud_AWS/terraform/module/examples/sock-shop-eks/variables.tf

Adding example of creating Elastic Kubernetes Service, deploying sock-shop app sending logs to bucket.

Sock shop aws example

---

cloud_GCP/ansible/roles/kentik_gcp_integration/tasks/main.yml
cloud_GCP/ansible/roles/kentik_gcp_integration/tests/test.yml

Adding workaround to not working :() operator

Fixing a bug of multiple subnets' logs not showing up

---

cloud_GCP/ansible/roles/kentik_gcp_integration/README.md
cloud_GCP/ansible/roles/kentik_gcp_integration/tasks/main.yml
cloud_GCP/ansible/roles/kentik_gcp_integration/tests/test.yml

Fixing bug introduced by "Adding workaround to not working :() operator" when creating resources from scratch.

Gcp ansible role bugfix

---

cloud_AWS/terraform/module/README.md
cloud_AWS/terraform/module/iam.tf
cloud_AWS/terraform/module/output.tf
cloud_AWS/terraform/module/variables.tf
cloud_GCP/terraform/module/flow_logs.tf

Additionally deletion of subnets flow logs on destroy added.

Add variable to turn of role creation 

---

.github/workflows/aws-terraform.yml
.github/workflows/azure-ansible.yml
cloud_AWS/terraform/module/README.md
cloud_AWS/terraform/module/cloudexport.tf
cloud_AWS/terraform/module/examples/all-vpc-from-region/main.tf
cloud_AWS/terraform/module/examples/single-vpc/main.tf
cloud_AWS/terraform/module/tests/main.tf
cloud_AWS/terraform/module/variables.tf

Added automatic exporting AWS cloud to kentik in terraform module

---

.github/workflows/azure-ansible.yml
.github/workflows/gcp-terraform.yml
cloud_GCP/terraform/module/README.md
cloud_GCP/terraform/module/cloudexport.tf
cloud_GCP/terraform/module/examples/all-network-subnets/README.md
cloud_GCP/terraform/module/examples/all-network-subnets/main.tf
cloud_GCP/terraform/module/examples/all-network-subnets/variables.tf
cloud_GCP/terraform/module/examples/subnet-list/README.md
cloud_GCP/terraform/module/examples/subnet-list/main.tf
cloud_GCP/terraform/module/examples/subnet-list/variables.tf
cloud_GCP/terraform/module/tests/main.tf
cloud_GCP/terraform/module/variables.tf

Added automatic exporting GCP cloud to kentik in terraform module

---

cloud_AWS/terraform/module/files/kentikEC2Access.json

Modified Terraform AWS module to include custom permissions policy

---

cloud_AWS/terraform/module/examples/multiple-aws-accounts-multiple-vpc-setup/README.md

Update README after changing terraform workspace naming approach

---

cloud_AWS/terraform/module/README.md
cloud_AWS/terraform/module/examples/all-vpc-from-region/README.md
cloud_AWS/terraform/module/examples/all-vpc-from-region/main.tf
cloud_AWS/terraform/module/examples/no-cloudexport/README.md
cloud_AWS/terraform/module/examples/no-cloudexport/main.tf
cloud_AWS/terraform/module/examples/single-vpc/README.md
cloud_AWS/terraform/module/examples/single-vpc/main.tf
cloud_AWS/terraform/module/variables.tf
cloud_GCP/terraform/module/README.md
cloud_GCP/terraform/module/examples/all-network-subnets/README.md
cloud_GCP/terraform/module/examples/all-network-subnets/variables.tf
cloud_GCP/terraform/module/examples/subnet-list/README.md
cloud_GCP/terraform/module/examples/subnet-list/variables.tf
cloud_GCP/terraform/module/variables.tf

Inspired by: https://github.com/kentik/config-snippets-cloud/pull/43

Improve AWS TF module docs

---

.github/workflows/azure-terraform.yml
cloud_AWS/terraform/module/tests/main.tf
cloud_Azure/README.md
cloud_Azure/terraform/module/README.md
cloud_Azure/terraform/module/cloudexport.tf
cloud_Azure/terraform/module/examples/all_nsg/README.md
cloud_Azure/terraform/module/examples/all_nsg/main.tf
cloud_Azure/terraform/module/examples/all_nsg/output.tf
cloud_Azure/terraform/module/examples/all_nsg/variables.tf
cloud_Azure/terraform/module/get_nsg.py
cloud_Azure/terraform/module/network_watcher.tf
cloud_Azure/terraform/module/output.tf
cloud_Azure/terraform/module/requirements.txt
cloud_Azure/terraform/module/roles.tf
cloud_Azure/terraform/module/service_principal.tf
cloud_Azure/terraform/module/storage_account.tf
cloud_Azure/terraform/module/tests/main.tf
cloud_Azure/terraform/module/variables.tf
synthetics_POC/terraform/README.md

KNTK-342
-  Configure CloudExport for single Subscription, multiple ResourceGroups
Based on https://github.com/kentik/config-snippets-cloud/pull/43

Cloudexport azure automation across resourcegroups

---

.github/workflows/aws-ansible.yml
cloud_Azure/terraform/module/cloudexport.tf
cloud_Azure/terraform/module/examples/multiple_accounts_multiple_resource_group/main.tf
cloud_Azure/terraform/module/examples/single_account_multiple_resource_groups/main.tf
cloud_Azure/terraform/module/tests/main.tf

KNTK-405
- Peg terraform providers to fixed major versions to prevent compatibility issues when new versions get released

Pegged terraform providers to fixed major versions

---

cloud_Azure/terraform/module/examples/multiple_accounts_multiple_resource_group/main.tf
cloud_Azure/terraform/module/examples/single_account_multiple_resource_groups/main.tf
cloud_Azure/terraform/module/network_watcher.tf
cloud_Azure/terraform/module/tests/main.tf

Upgrade Terraform providers for Azure after new major version release

Upgrade Terraform providers for Azure after new major version release

---

.github/workflows/aws-ansible.yml
cloud_AWS/terraform/module/s3.tf
cloud_Azure/terraform/module/cloudexport.tf
cloud_Azure/terraform/module/examples/multiple_accounts_multiple_resource_group/main.tf
cloud_Azure/terraform/module/examples/single_account_multiple_resource_groups/main.tf
cloud_Azure/terraform/module/tests/main.tf

flowlog v5 formatting / fields (from v2)

flow v5 formatting (from v2)

---

README.md

Adding Swagger doc reference

---

.github/workflows/static-analysis.yml
cloud_AWS/terraform/module/examples/sock-shop-eks/k8s_1.16/1-sock-shop-install/sock-shop-complete-demo.yaml
cloud_Azure/terraform/module/examples/multiple_accounts_multiple_resource_group/profiles_tool.py
cloud_Azure/terraform/module/get_nsg.py
synthetics_POC/terraform/init.sh.tpl

This change takes more cautious approach than https://github.com/kentik/config-snippets-cloud/pull/59 and does not make substantial changes to the code.
Disabled linters can be configured enabled one-by-one in the future.

Configure Super-Linter

---

cloud_AWS/terraform/module/iam.tf

all names have dashes. before it was some with dashes some without. Box asked to make it consistent.

Set aws iam file to have all dashes. 
